on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main 

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic info"
        run: |
            echo " REF: $GITHUB_REF"
            echo "Job ID: $GITHUB_JOB"
            echo "Actions: $GITHUB_ACTION"
            echo "Actor: $GITHUB_ACTOR"

