on:
  schedule:
    - cron: '*/10 20 * * 0'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps: 
      - name: run every 8 o clock every sunday 
        run: | 
          current_time=$(date +'%H:%M')
          if [ "$current_time" -eq "20:00" ]
          then 
            echo "This step runs only at exactly 8:00 PM"
          else 
            echo "Skipping because it's not exactly 8:00 PM"
